# This file was generated by GoReleaser. DO NOT EDIT.
cask "bc-local" do
  name "bc-local"
  desc "Local BriteCore Dev Environment"
  homepage ""
  version "0.15.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bc-local"
  depends_on cask: [
      "podman-desktop",
    ],
    formula: [
      "awscli",
      "gettext",
      "gh",
      "go-task",
      "helm",
      "jq",
      "kind",
      "kubectl",
      "podman",
      "sops",
      "uv",
      "yq",
    ]

  on_macos do
    on_intel do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v#{version}/bc-local_#{version}_darwin_amd64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "45ced24e93d2c62273532fa18932ba67c14e95bf97d22d5c209529647aed4b07"
    end
    on_arm do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v#{version}/bc-local_#{version}_darwin_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "fdcee9bb45e46d084069c60d78a7b590f777436e038e0dbec13f421b2bd2ea26"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v#{version}/bc-local_#{version}_linux_amd64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "37d7a7d1259e8501a7acbee81c4e8df71c0f594cf09919071be1043e9524c2a1"
    end
    on_arm do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v#{version}/bc-local_#{version}_linux_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "80f4953275783c0e8a933db1f7b943da5a24689f14e358767156fd1191187c57"
    end
  end

  postflight do
    ENV['PATH'] = "/opt/homebrew/bin:/usr/local/bin:~/.local/bin:#{ENV['PATH']}"

    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bc-local"]
    end

    # Check if britecore-cli is already installed
    if !File.executable?("#{Dir.home}/.local/bin/britecore-cli")
      puts "britecore-cli not found, installing..."

      # Find task binary in common locations
      task_binary = nil
      ["/opt/homebrew/bin/task", "/usr/local/bin/task", "/usr/bin/task"].each do |path|
        if File.executable?(path)
          task_binary = path
          break
        end
      end

      if task_binary
        puts "Using task binary at: #{task_binary}"
        system_command task_binary, args: ["-t", "#{staged_path}/Taskfile.yaml", "install-cli"]
      else
        puts "Warning: task binary not found. Please install go-task and run 'task install-cli' manually."
      end
    else
      puts "britecore-cli already installed at ~/.local/bin/britecore-cli"
    end
  end

  # No zap stanza required
end
