# This file was generated by GoReleaser. DO NOT EDIT.
cask "bc-local-beta" do
  desc "Local BriteCore Dev Environment (Beta)"
  homepage ""
  version "0.7.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bc-local-beta"
  depends_on cask: [
      "podman-desktop",
    ],
    formula: [
      "awscli",
      "gettext",
      "go-task",
      "helm",
      "jq",
      "kind",
      "kubectl",
      "podman",
      "sops",
      "yq",
    ]

  on_macos do
    on_intel do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v0.7.5/bc-local-beta_0.7.5_darwin_amd64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "0c7297e47dc93594d2874b755071a8e72ed58f67982000e56992041244fc1cb6"
    end
    on_arm do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v0.7.5/bc-local-beta_0.7.5_darwin_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "67086e09873bc37dcd3e5f636e8449894a5b3f0c95fde7550c0b5c666c724a64"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v0.7.5/bc-local-beta_0.7.5_linux_amd64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "f0478e252a3a173b55158ea9a2d337b61f0fb6b4e99e8f133ee22feca8a9a7e1"
    end
    on_arm do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v0.7.5/bc-local-beta_0.7.5_linux_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "6aa124f660be76da9e6feaf4d43cf39aedad670cc20ab00405bf434f746f2c86"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/bin/chmod", args: ["+x", "#{staged_path}/scripts/db-connect.sh"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bc-local-beta"]
    end
  end

  # No zap stanza required
end
