# This file was generated by GoReleaser. DO NOT EDIT.
cask "bc-local" do
  name "bc-local"
  desc "Local BriteCore Dev Environment"
  homepage ""
  version "0.15.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bc-local"
  depends_on cask: [
      "podman-desktop",
    ],
    formula: [
      "awscli",
      "gettext",
      "gh",
      "go-task",
      "helm",
      "jq",
      "kind",
      "kubectl",
      "podman",
      "sops",
      "uv",
      "yq",
    ]

  on_macos do
    on_intel do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v#{version}/bc-local_#{version}_darwin_amd64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "3aed59c2e038ac5a1937dfbf44995e146ca5f86e4caa4d4a067d4373ab7a2e60"
    end
    on_arm do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v#{version}/bc-local_#{version}_darwin_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "28105217985a9ba5c486fb60f667f55bf454f919731eff6dd521bb1cb7a6126d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v#{version}/bc-local_#{version}_linux_amd64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "7042759ec60624d68a1996334d76e1dd7ff71809def6acca13db086a9eca7486"
    end
    on_arm do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v#{version}/bc-local_#{version}_linux_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "5cec35910c7e086d8f2d209ce3af22066371c59755058c548ba06e907ce72728"
    end
  end

  postflight do
    ENV['PATH'] = "/opt/homebrew/bin:/usr/local/bin:~/.local/bin:#{ENV['PATH']}"

    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bc-local"]
    end

    # Check if britecore-cli is already installed
    if !File.executable?("#{Dir.home}/.local/bin/britecore-cli")
      puts "britecore-cli not found, installing..."

      # Find task binary in common locations
      task_binary = nil
      ["/opt/homebrew/bin/task", "/usr/local/bin/task", "/usr/bin/task"].each do |path|
        if File.executable?(path)
          task_binary = path
          break
        end
      end

      if task_binary
        puts "Using task binary at: #{task_binary}"
        system_command task_binary, args: ["-t", "#{staged_path}/Taskfile.yaml", "install-cli"]
      else
        puts "Warning: task binary not found. Please install go-task and run 'task install-cli' manually."
      end
    else
      puts "britecore-cli already installed at ~/.local/bin/britecore-cli"
    end
  end

  # No zap stanza required
end
