# This file was generated by GoReleaser. DO NOT EDIT.
cask "bc-local" do
  desc "Local BriteCore Dev Environment"
  homepage ""
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bc-local"
  depends_on cask: [
      "podman-desktop",
    ],
    formula: [
      "awscli",
      "gettext",
      "go-task",
      "helm",
      "jq",
      "kind",
      "kubectl",
      "podman",
      "sops",
      "yq",
    ]

  on_macos do
    on_intel do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v0.0.1/bc-local_0.0.1_darwin_amd64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "5df7e566f0a9c676f452c0ec144bddc55c821154b35299ac4fb45f4af7f95317"
    end
    on_arm do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v0.0.1/bc-local_0.0.1_darwin_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "eab2bded968658c6a9c9cdc6e7e2e1f5ac124425ecf69f57bab07a61fe5204a3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v0.0.1/bc-local_0.0.1_linux_amd64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "38b314e90a3344f479ce0e787d355ee92fbda4cde318eb31a5f5c479302c7cd2"
    end
    on_arm do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v0.0.1/bc-local_0.0.1_linux_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "8809fb231fe49563130bfadc4d0f9072af8f1e1b83539c57937ecc44613c75b2"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/bin/chmod", args: ["+x", "#{staged_path}/db-connect.sh"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bc-local"]
    end
  end

  # No zap stanza required
end
