# This file was generated by GoReleaser. DO NOT EDIT.
cask "bc-local-beta" do
  desc "Local BriteCore Dev Environment (Beta)"
  homepage ""
  version "0.7.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bc-local-beta"
  depends_on cask: [
      "podman-desktop",
    ],
    formula: [
      "awscli",
      "gettext",
      "go-task",
      "helm",
      "jq",
      "kind",
      "kubectl",
      "podman",
      "sops",
      "yq",
    ]

  on_macos do
    on_intel do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v0.7.4/bc-local-beta_0.7.4_darwin_amd64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "9570ea78d1822eba9a6305614139e1319641bde7c6257c71b278cc3e01470231"
    end
    on_arm do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v0.7.4/bc-local-beta_0.7.4_darwin_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "6bcece61a6dd7f6af7ec7aec75b75af0531b167a2bbf47cdc90e32bc2d5fa836"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v0.7.4/bc-local-beta_0.7.4_linux_amd64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "51aca49599b75937e38d2dd73ba80e0ad0eb395dbe39fc833644ab34016d0977"
    end
    on_arm do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v0.7.4/bc-local-beta_0.7.4_linux_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "c046e139f8f865a94a78bf14e194a07f4f5ec5f3a6143539edf1dc8a0d932dc3"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bc-local-beta"]
    end
  end

  # No zap stanza required
end
