# This file was generated by GoReleaser. DO NOT EDIT.
cask "bc-local-beta" do
  desc "Local BriteCore Dev Environment (Beta)"
  homepage ""
  version "0.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bc-local-beta"
  depends_on cask: [
      "podman-desktop",
    ],
    formula: [
      "awscli",
      "gettext",
      "go-task",
      "helm",
      "jq",
      "kind",
      "kubectl",
      "podman",
      "sops",
      "yq",
    ]

  on_macos do
    on_intel do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v0.0.0/bc-local-beta_0.0.0_darwin_amd64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "cbbb47a182c503ecefda01566697195224e844390f487774ed405fad9d6cb877"
    end
    on_arm do
      url "https://github.com/IntuitiveWebSolutions/bc-local/releases/download/v0.0.0/bc-local-beta_0.0.0_darwin_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{GitHub::API.credentials}",
        ]
      sha256 "b9435cfa2aa4cb68b238acb6af5aa595248f0732ae81eb50f4df5ef00a7f5dce"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bc-local-beta"]
    end
  end

  # No zap stanza required
end
